/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseGraph: typeof import('./src/components/BaseGraph.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    TemperatureGraph: typeof import('./src/components/TemperatureGraph.vue')['default']
  }
}
